CREATE TYPE public.user_type AS ENUM ('user', 'sup', 'admin');

CREATE TABLE IF NOT EXISTS "asset_type"
(
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS "project" 
(
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(40) NOT NULL,
	shortName varchar(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS "user"
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	userId varchar(100) not null,
	name varchar(100) NOT NULL,
	enabled integer NOT NULL DEFAULT 1,
	userType USER_TYPE NOT NULL DEFAULT 'user',
	fk_project_id integer REFERENCES project(id)
);

CREATE TABLE IF NOT EXISTS "auth"
(
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	userName varchar(40) NOT NULL,
	password varchar(300) NOT NULL,
	fk_user_id integer REFERENCES public.user(id)
);


ALTER TABLE public.asset ADD COLUMN type varchar(40);

CREATE TABLE IF NOT EXISTS "asset"
(
	id integer GENERATED BY DEFAULT AS IDENTITY,
	serial varchar(40) PRIMARY KEY NOT NULL,
	model varchar(40) NOT NULL,
	brand varchar(40) NOT NULL,
	size varchar(20),
	disposed integer DEFAULT 0,
	disposed_date date,
	disposed_reason varchar(200),
	type integer
	fk_user_id integer REFERENCES public.user(id),
);
