CREATE TYPE public.user_type AS ENUM ('user', 'sup', 'admin');

CREATE TABLE IF NOT EXISTS "asset_type"
(
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS "project" 
(
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(40) NOT NULL,
	shortName varchar(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS "user"
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	userId varchar(100) not null,
	name varchar(100) NOT NULL,
	enabled integer NOT NULL DEFAULT 1,
	userType USER_TYPE NOT NULL DEFAULT 'user',
	fk_project_id integer REFERENCES project(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "auth"
(
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	userName varchar(40) NOT NULL,
	password varchar(300) NOT NULL,
	fk_user_id integer REFERENCES public.user(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS "asset"
(
	id integer GENERATED BY DEFAULT AS IDENTITY,
	serial varchar(40) PRIMARY KEY NOT NULL,
	model varchar(40) NOT NULL,
	brand varchar(40) NOT NULL,
	size varchar(20),
	disposed integer DEFAULT 0,
	disposed_date date,
	disposed_reason varchar(200),
	type varchar (40),
	fk_user_id integer REFERENCES public.user(id) ON DELETE SET NULL
);

INSERT INTO public.user (name, userid, usertype) VALUES ("Administrator", "000001", "admin");

--Setup auth user, pass is hashed, password is: Administrator1234$, make sure to change it after deployment.
INSERT INTO public.auth (username, password, fk_user_id) VALUES ("administrator","$2b$10$OXpDzA9CUvrBWXg8zRvX6u2FAVGlVEEm3aJ4pb2jhKQ4HnqQdpTUK", 1)

