@host = http://localhost:3000

### Create user
post {{host}}/auth/signup
Content-Type: application/json

{
  "user": {
    "name": "Administrator",
    "userid": "0000001",
    "usertype": "admin"
  },
  "auth": {
    "username": "administrator",
    "password": "Administrator1234$"
  }
}

### Login user
# @name login
post {{host}}/auth/login
Content-Type: application/json

{
  "userName": "WilsonOmar",
  "password": "Omar4291."
}

### Test authentication
# @name user
@access_token = {{login.response.body.token}}
post {{host}}/auth/check
Content-Type: application/json
Authorization: Bearer {{access_token}}


